export const SET_IS_LOADING = 'SET_IS_LOADING'
export const SET_ERROR_MESS = 'SET_ERROR_MESS'
export const CHARACTER_FETCH = 'CHARACTER_FETCH'
export const SET_CHARACTER = 'SET_CHARACTER'
export const EPISODE_FETCH = 'EPISODE_FETCH'
export const SET_EPISODE = 'SET_EPISODE'

